-- Protects against the same visit being saved twice.
--
-- Plain-English summary: each time the "Log interaction" form is opened
-- it gets its own random ID, which is sent along when it's saved. If the
-- same form is submitted twice -- a double tap on a slow connection, or
-- tapping Save again because the first attempt seemed to hang but had
-- actually gone through -- the database recognizes the ID and refuses a
-- second copy, and the app treats the first save as the answer.
--
-- The column is optional: every existing interaction simply has none.

alter table public.interactions
  add column client_submission_id uuid;

comment on column public.interactions.client_submission_id is
  'Random ID generated by the log-interaction form, used to make saving idempotent (no duplicate rows from double submits or retries). Null for rows created any other way.';

create unique index interactions_client_submission_id_key
  on public.interactions (client_submission_id)
  where client_submission_id is not null;
